package mcf

import (
	"encoding/json"
	"os"
	"testing"
)

// TestJobDecodeLiveShapes decodes a captured real GET /v2/jobs response.
//
// Why this exists: testdata/fixture/jobs.jsonl is generated by
// scripts/genfixture from these very structs, so it agrees with whatever the
// structs say — including when they are wrong. On 2026-08-03 five fields were
// modeled as strings that the live API returns as objects; every page failed to
// decode in production while the self-generated fixture kept CI green.
//
// testdata/live/jobs-page.json is a real response instead (publisher-personal
// fields createdBy/emailRecipient stripped per docs/01 §5), so a struct that
// drifts from the API fails here.
func TestJobDecodeLiveShapes(t *testing.T) {
	b, err := os.ReadFile("../../testdata/live/jobs-page.json")
	if err != nil {
		t.Fatalf("read live capture: %v", err)
	}

	// The real client decodes a whole Page; one bad job must not be maskable.
	var page Page
	if err := json.Unmarshal(b, &page); err != nil {
		t.Fatalf("decode live page: %v", err)
	}
	if len(page.Results) == 0 {
		t.Fatal("live capture has no results")
	}

	// The envelope regressed too: _links entries are {"href":...} objects, and
	// modeling them as *string failed the page before any job was reached.
	if page.Links == nil || page.Links.Next == nil || page.Links.Next.Href == "" {
		t.Error("_links.next.href not populated — envelope shape does not match the live API")
	}

	// Every job must carry the fields the pipeline depends on. These are the
	// ones the /v2/search projection omits, so this also pins "list == detail".
	for i, j := range page.Results {
		if j.UUID == "" {
			t.Errorf("job %d: empty uuid", i)
		}
		if j.Title == "" {
			t.Errorf("job %d (%s): empty title", i, j.UUID)
		}
		if j.Description == "" {
			t.Errorf("job %d (%s): empty description — tech extraction has nothing to read", i, j.UUID)
		}
		if j.SSOCCode == "" {
			t.Errorf("job %d (%s): empty ssocCode — is_candidate/role_family degrade", i, j.UUID)
		}
		if j.Metadata.JobPostID == "" {
			t.Errorf("job %d (%s): empty metadata.jobPostId", i, j.UUID)
		}
		if j.Metadata.NewPostingDate == "" {
			t.Errorf("job %d (%s): empty metadata.newPostingDate — the incremental watermark", i, j.UUID)
		}
	}

	// The five shapes that regressed. Assert the nested label actually lands,
	// not merely that decoding succeeded: a wrong-but-decodable type (say
	// []struct{} with no matching tag) yields empty strings and would slip past.
	var sawEmpType, sawFWA, sawScheme, sawSalaryType, sawDistrict bool
	for _, j := range page.Results {
		for _, e := range j.EmploymentTypes {
			if e.EmploymentType != "" {
				sawEmpType = true
			}
		}
		for _, f := range j.FlexibleWorkArrangements {
			if f.FlexibleWorkArrangement != "" {
				sawFWA = true
			}
		}
		for _, s := range j.Schemes {
			if s.Scheme.Scheme != "" {
				sawScheme = true
			}
		}
		if j.Salary != nil && j.Salary.Type.SalaryType != "" {
			sawSalaryType = true
		}
		if j.Address != nil {
			for _, d := range j.Address.Districts {
				if d.Location != "" {
					sawDistrict = true
				}
			}
		}
	}
	for _, c := range []struct {
		name string
		ok   bool
	}{
		{"employmentTypes[].employmentType", sawEmpType},
		{"flexibleWorkArrangements[].flexibleWorkArrangement", sawFWA},
		{"schemes[].scheme.scheme", sawScheme},
		{"salary.type.salaryType", sawSalaryType},
		{"address.districts[].location", sawDistrict},
	} {
		if !c.ok {
			t.Errorf("%s never populated — struct shape does not match the live API", c.name)
		}
	}
}

// TestWorkArrangementsProjection covers the []object -> []string projection
// classify.WorkMode consumes.
func TestWorkArrangementsProjection(t *testing.T) {
	j := Job{FlexibleWorkArrangements: []FlexibleWorkArrangement{
		{ID: 1, FlexibleWorkArrangement: "Hybrid"},
		{ID: 2, FlexibleWorkArrangement: "Creative Scheduling"},
	}}
	got := j.WorkArrangements()
	if len(got) != 2 || got[0] != "Hybrid" || got[1] != "Creative Scheduling" {
		t.Errorf("WorkArrangements() = %v, want [Hybrid, Creative Scheduling]", got)
	}
	if len(Job{}.WorkArrangements()) != 0 {
		t.Error("WorkArrangements() on zero Job should be empty")
	}
}
